#!/usr/bin/env python
"""Generate one finetune.py config per bootstrap replicate, plus a driver script.

Each replicate written by bootstrap_subsample.py becomes one fine-tuning run, and the spread
across the resulting models is the ensemble's uncertainty estimate. finetune.py already accepts
--config_path (finetune.py:670), so driving 10 runs needs no training-code change -- only 10
configs that differ in the right places and agree everywhere else.

Exactly three things may differ between members, or the ensemble stops measuring what it should:

    job_id              the wandb run name (finetune.py:559)
    ar_index_train      the replicate
    path_experiment     where checkpoints land

Everything else -- and in particular the evaluation indices -- is held identical. Members have to
be scored on the same data; if validation were resampled per member, the observed spread would be
model variance plus evaluation-set variance with no way to separate them.

Three fixes are applied to every generated config because the shipped config.yaml cannot run the
ensemble as-is:

  1. ar_mask_root_path points at /home/jovyan/scratch_space/... which does not exist, so
     dataset.py:63 raises FileNotFoundError before training starts. Repointed at the assets copy.
  2. path_experiment is one global "checkpoints" dir, and finetune.py:657-659 writes
     epoch_{epoch}.pth there unconditionally every epoch -- all 10 runs would overwrite each
     other, and 15 epochs x 10 members at ~1.8 GB is ~250 GB against 26 GB free on /home/jovyan.
     Moved to a per-member directory under --experiment-root (default on /efs).
  3. iters_per_epoch_train is 2000 against a 168-sample epoch. Harmless (finetune.py:610 uses it
     only as a break cap) but it makes the logs misleading, so it is set to the replicate size.

Usage:
    python make_bootstrap_configs.py
    python make_bootstrap_configs.py --max-epochs 5
    python make_bootstrap_configs.py --replicate-dir assets/bootstrap_train_1week
"""

import argparse
import copy
import glob
import os
import stat

import pandas as pd
import yaml

HEADER = """\
# GENERATED by make_bootstrap_configs.py -- do not edit by hand.
#
# Bootstrap ensemble member {rep} of {total}.
#   training index : {train}  ({n_rows} samples)
#   checkpoints    : {experiment}
#
# Evaluation indices are identical across all {total} members on purpose: members must be
# scored on the same data, or model variance and evaluation-set variance are confounded.
# Regenerate with: python make_bootstrap_configs.py
"""

RUNNER = """\
#!/usr/bin/env bash
# GENERATED by make_bootstrap_configs.py -- runs the bootstrap ensemble sequentially.
#
# Each member is an independent fine-tune on its own 1-week bootstrap replicate. Checkpoints go
# to per-member directories, so members never overwrite one another and the script deletes
# nothing.
#
# Cost per member: {n_rows} samples x ~590 MB of SDO NetCDF per epoch = ~{gb_epoch:.0f} GB/epoch,
# re-fetched each epoch because files are deleted after use. At {epochs} epochs that is
# ~{tb_member:.1f} TB per member and ~{tb_total:.0f} TB for the ensemble; max_epochs is the main
# lever on wall time.
set -euo pipefail

cd "$(dirname "${{BASH_SOURCE[0]}}")"

# The allocator fragments on long runs at 4096x4096; expandable segments lets it reuse that
# memory, as run_g4dn_test.sh does.
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

{runs}
echo "All {total} members complete."
"""

RUN_LINE = """\
echo "=== member {rep}/{total}: {config} ==="
torchrun --nnodes=1 --nproc_per_node=1 --standalone finetune.py \\
    --gpu{wandb} --config_path ./{config}
"""


def main() -> None:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("--base-config", default="./config.yaml",
                   help="Config to derive every member from.")
    p.add_argument("--replicate-dir", default="./assets/bootstrap_train_1week",
                   help="Directory of replicate indices from bootstrap_subsample.py.")
    p.add_argument("--replicate-glob", default="*_boot[0-9][0-9][0-9].csv",
                   help="Which files in --replicate-dir are replicates (excludes the manifest).")
    p.add_argument("--out-dir", default="./configs_bootstrap",
                   help="Where the generated configs are written.")
    p.add_argument("--runner", default="./run_bootstrap_ensemble.sh",
                   help="Where the driver script is written. It must sit in this example's "
                        "directory, not in --out-dir: finetune.py and every asset path in the "
                        "configs resolve against the working directory, and the runner cds to "
                        "its own location.")
    p.add_argument("--experiment-root", default="/efs/bathomas/ar_seg_bootstrap",
                   help="Parent of the per-member checkpoint directories. Keep this off "
                        "/home/jovyan, which has ~26 GB free against ~250 GB of checkpoints.")
    p.add_argument("--valid-index", default="./assets/surya-bench-ar-segmentation/validation.csv",
                   help="Fixed validation index, identical for every member. The full split is "
                        "the default deliberately: iters_per_epoch_valid caps evaluation at 200 "
                        "batches either way, so a smaller index costs the same while covering "
                        "far less -- ar_index_validation_1day.csv spans only Jan 15 of each year "
                        "(9 days) against 153 days here. Per-member metric noise feeds straight "
                        "into the ensemble spread, so broader coverage is worth having free.")
    p.add_argument("--test-index", default="./assets/surya-bench-ar-segmentation/leaky_validation.csv",
                   help="Fixed leaky-validation index, identical for every member. The full split "
                        "is the default for the same reason as --valid-index: the 1day subsample "
                        "covers only Jan 1 and Feb 1 of each year (18 days) against 252 days "
                        "here. NOTE: finetune.py never reads ar_index_test -- it is carried for "
                        "post-hoc evaluation -- and nothing shipped indexes its Jan 1-14 / "
                        "Feb 1-14 SDO inputs, so it yields 0 samples until that index is built "
                        "from S3 (make_month_start_subsets.py --with-sdo-index).")
    p.add_argument("--ar-mask-root", default="./assets/surya-bench-ar-segmentation",
                   help="Directory holding the mask .h5 tree.")
    p.add_argument("--s3-scratch-dir", default="/tmp/surya_s3_scratch",
                   help="Staging dir for SDO objects. Needs ~5 GB (8 workers x ~590 MB).")
    p.add_argument("--max-epochs", type=int, default=10,
                   help="optimizer.max_epochs. Pass 0 to inherit the base config's value.")

    # Model capacity. The base config.yaml is rank-32/alpha-64 with no activation
    # checkpointing, which is tuned for a large GPU and a large training set. These defaults
    # match config_feb16_2013.yaml instead: far less adapter capacity for a 168-sample member,
    # and recompute on half the blocks so the run fits comfortably in memory.
    p.add_argument("--lora-r", type=int, default=8, help="model.lora_config.r.")
    p.add_argument("--lora-alpha", type=int, default=16, help="model.lora_config.lora_alpha.")
    p.add_argument("--checkpoint-layers", default="0,2,4,6,8",
                   help="Comma-separated block indices to activation-checkpoint, or 'none' for "
                        "no checkpointing. Default: 5 of the 10 blocks.")

    p.add_argument("--wandb-from", default="./config_feb15_2013_g4dn.yaml",
                   help="Copy every wandb_* key from this config. finetune.py:558,561 fall back "
                        "to entity 'nasa-impact' and mode 'offline' when the keys are absent, "
                        "so without this the runs would log to the wrong place. Pass 'none' to "
                        "keep the base config's wandb settings.")
    p.add_argument("--no-wandb", action="store_true",
                   help="Omit --wandb from the generated runner. wandb.init only happens when "
                        "finetune.py is given that flag, so the wandb_* keys are inert without it.")
    args = p.parse_args()

    base = yaml.safe_load(open(args.base_config))
    reps = sorted(glob.glob(os.path.join(args.replicate_dir, args.replicate_glob)))
    if not reps:
        raise SystemExit(
            f"No replicates matching {args.replicate_glob} in {args.replicate_dir}. "
            f"Run bootstrap_subsample.py first."
        )

    for path in (args.valid_index, args.test_index):
        if not os.path.isfile(path):
            raise SystemExit(f"Evaluation index not found: {path}")
    if not os.path.isdir(args.ar_mask_root):
        raise SystemExit(f"Mask directory not found: {args.ar_mask_root}")

    os.makedirs(args.out_dir, exist_ok=True)
    epochs = args.max_epochs or base["optimizer"]["max_epochs"]
    total = len(reps)
    run_lines, rows = [], []

    ckpt_layers = (
        [] if args.checkpoint_layers.strip().lower() == "none"
        else [int(x) for x in args.checkpoint_layers.split(",")]
    )

    wandb_keys = {}
    if args.wandb_from.strip().lower() != "none":
        if not os.path.isfile(args.wandb_from):
            raise SystemExit(f"--wandb-from config not found: {args.wandb_from}")
        src = yaml.safe_load(open(args.wandb_from))
        wandb_keys = {k: v for k, v in src.items() if k.startswith("wandb")}
        if not wandb_keys:
            raise SystemExit(f"No wandb_* keys found in {args.wandb_from}")

    for i, rep_path in enumerate(reps, start=1):
        n_rows = len(pd.read_csv(rep_path))
        cfg = copy.deepcopy(base)

        # --- the three per-member differences ---
        cfg["job_id"] = f"AR-seg_boot{i:02d}"
        cfg["data"]["ar_index_train"] = [f"./{os.path.relpath(rep_path, '.')}"]
        experiment = os.path.join(args.experiment_root, f"boot{i:02d}")
        cfg["path_experiment"] = experiment

        # --- held identical across members ---
        cfg["data"]["ar_index_valid"] = [args.valid_index]
        cfg["data"]["ar_index_test"] = [args.test_index]

        # --- corrections to the shipped config ---
        cfg["data"]["ar_mask_root_path"] = args.ar_mask_root
        cfg["data"]["s3_scratch_dir"] = args.s3_scratch_dir
        cfg["iters_per_epoch_train"] = n_rows
        cfg["optimizer"]["max_epochs"] = epochs

        # --- capacity / memory, and wandb destination ---
        cfg["model"]["lora_config"]["r"] = args.lora_r
        cfg["model"]["lora_config"]["lora_alpha"] = args.lora_alpha
        cfg["model"]["checkpoint_layers"] = list(ckpt_layers)
        cfg.update(wandb_keys)

        name = f"config_boot{i:02d}.yaml"
        out = os.path.join(args.out_dir, name)
        with open(out, "w") as fh:
            fh.write(HEADER.format(rep=i, total=total, train=rep_path, n_rows=n_rows,
                                   experiment=experiment))
            yaml.safe_dump(cfg, fh, sort_keys=False, default_flow_style=False)

        run_lines.append(RUN_LINE.format(rep=i, total=total,
                                         wandb="" if args.no_wandb else " --wandb",
                                         config=os.path.relpath(out, ".")))
        rows.append({"member": i, "config": out, "ar_index_train": rep_path,
                     "n_rows": n_rows, "path_experiment": experiment})

    n_rows = rows[0]["n_rows"]
    gb_epoch = n_rows * 590 / 1000
    runner_path = args.runner
    with open(runner_path, "w") as fh:
        fh.write(RUNNER.format(total=total, n_rows=n_rows, epochs=epochs, gb_epoch=gb_epoch,
                               tb_member=gb_epoch * epochs / 1000,
                               tb_total=gb_epoch * epochs * total / 1000,
                               runs="\n".join(run_lines)))
    os.chmod(runner_path, os.stat(runner_path).st_mode | stat.S_IXUSR | stat.S_IXGRP)

    index = pd.DataFrame(rows)
    index_path = os.path.join(args.out_dir, "ensemble_index.csv")
    index.to_csv(index_path, index=False)

    print(f"wrote {total} member config(s) to {args.out_dir}")
    print(f"  runner:   {runner_path}")
    print(f"  index:    {index_path}")
    print(f"  epochs:   {epochs}   samples/member: {n_rows}")
    print(f"  lora:     r={args.lora_r} alpha={args.lora_alpha}   "
          f"checkpoint_layers={ckpt_layers}")
    if wandb_keys:
        print(f"  wandb:    from {args.wandb_from} -> "
              + ", ".join(f"{k}={v!r}" for k, v in sorted(wandb_keys.items())))
        if args.no_wandb:
            print("            NOTE: --no-wandb, so the runner omits --wandb and these are inert")
    print(f"  valid:    {args.valid_index}   (identical for all {total})")
    print(f"  test:     {args.test_index}   (carried only; finetune.py does not read it)")
    print(f"  masks:    {args.ar_mask_root}")
    print(f"  ckpt dir: {args.experiment_root}/boot01 .. boot{total:02d}")
    print(index[["member", "ar_index_train", "n_rows"]].to_string(index=False))
    print(f"\nrun with:  bash {runner_path}")


if __name__ == "__main__":
    main()
