#!/usr/bin/env bash
# GENERATED by make_bootstrap_configs.py -- runs the bootstrap ensemble sequentially.
#
# Each member is an independent fine-tune on its own 1-week bootstrap replicate. Checkpoints go
# to per-member directories, so members never overwrite one another and the script deletes
# nothing.
#
# Cost per member: 168 samples x ~590 MB of SDO NetCDF per epoch = ~99 GB/epoch,
# re-fetched each epoch because files are deleted after use. At 10 epochs that is
# ~1.0 TB per member and ~10 TB for the ensemble; max_epochs is the main
# lever on wall time.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

# The allocator fragments on long runs at 4096x4096; expandable segments lets it reuse that
# memory, as run_g4dn_test.sh does.
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

echo "=== member 1/10: configs_bootstrap/config_boot01.yaml ==="
torchrun --nnodes=1 --nproc_per_node=1 --standalone finetune.py \
    --gpu --wandb --config_path ./configs_bootstrap/config_boot01.yaml

echo "=== member 2/10: configs_bootstrap/config_boot02.yaml ==="
torchrun --nnodes=1 --nproc_per_node=1 --standalone finetune.py \
    --gpu --wandb --config_path ./configs_bootstrap/config_boot02.yaml

echo "=== member 3/10: configs_bootstrap/config_boot03.yaml ==="
torchrun --nnodes=1 --nproc_per_node=1 --standalone finetune.py \
    --gpu --wandb --config_path ./configs_bootstrap/config_boot03.yaml

echo "=== member 4/10: configs_bootstrap/config_boot04.yaml ==="
torchrun --nnodes=1 --nproc_per_node=1 --standalone finetune.py \
    --gpu --wandb --config_path ./configs_bootstrap/config_boot04.yaml

echo "=== member 5/10: configs_bootstrap/config_boot05.yaml ==="
torchrun --nnodes=1 --nproc_per_node=1 --standalone finetune.py \
    --gpu --wandb --config_path ./configs_bootstrap/config_boot05.yaml

echo "=== member 6/10: configs_bootstrap/config_boot06.yaml ==="
torchrun --nnodes=1 --nproc_per_node=1 --standalone finetune.py \
    --gpu --wandb --config_path ./configs_bootstrap/config_boot06.yaml

echo "=== member 7/10: configs_bootstrap/config_boot07.yaml ==="
torchrun --nnodes=1 --nproc_per_node=1 --standalone finetune.py \
    --gpu --wandb --config_path ./configs_bootstrap/config_boot07.yaml

echo "=== member 8/10: configs_bootstrap/config_boot08.yaml ==="
torchrun --nnodes=1 --nproc_per_node=1 --standalone finetune.py \
    --gpu --wandb --config_path ./configs_bootstrap/config_boot08.yaml

echo "=== member 9/10: configs_bootstrap/config_boot09.yaml ==="
torchrun --nnodes=1 --nproc_per_node=1 --standalone finetune.py \
    --gpu --wandb --config_path ./configs_bootstrap/config_boot09.yaml

echo "=== member 10/10: configs_bootstrap/config_boot10.yaml ==="
torchrun --nnodes=1 --nproc_per_node=1 --standalone finetune.py \
    --gpu --wandb --config_path ./configs_bootstrap/config_boot10.yaml

echo "All 10 members complete."
